### ISSUE TITLE
Logs?

### ISSUE THREAD

**Issue by rpgoldman** [3b/ci-example#3]
Would it be possible for you to share some logs?  I looked under "Actions" on this repo, but all of the logs have timed out and been deleted.

Maybe you could kick it to make it run again?

Curious because we have tried using your template, but have not successfully gotten things to turn over: Roswell is only running SBCL; for some reason it never runs CCL (although it sees that entry in the matrix).

Thanks!

**Comment by 3b** [comment]
ran it again, and looks like the stuff they changed after I wrote it that broke things. will try to fix it soon
